### ISSUE TITLE
Architecture dependant page size

### ISSUE THREAD

**Issue by banditopazzo** [Reeywhaar/nut#7]
Looking a the code of `bbolt`, it uses `int` for page size.

using a `u32` in `nut` breaks compatibility for some architectures: https://github.com/Reeywhaar/nut/blob/0dac83cfc8446fa9e99e72deeb4a1e678ddcb106/src/meta/mod.rs#L26-L27

In normal cases it is better to be platform independent but in this case the "official" implementation is platform dependent and I think we should stick with that in order to be compatible

**Comment by reeywhaar** [comment]
Somehow I missed it in original bolt code 🤔 What do you suggest?

**Comment by banditopazzo** [comment]
Quoting the golang doc https://tour.golang.org/basics/11:
> The int, uint, and uintptr types are usually 32 bits wide on 32-bit systems and 64 bits wide on 64-bit systems

I suggest we should use `isize` being "usually" equal to Golang `int`

**Comment by reeywhaar** [comment]
Yeah, agree, I understand, yet it would be breaking change then. Though if we see this as compatibility fix it is not 🤔

**Comment by banditopazzo** [comment]
update: reading more code seems they are using `int` somewhere and `uint32` somewhere else, it's very weird. in the `DB struct` is `int`, while in ` Meta struct` is `uint32`

**Comment by reeywhaar** [comment]
Yeah, tried to naively change to usize and tests with bolt made database failed

<img width="262" alt="image" src="https://github.com/Reeywhaar/nut/assets/884649/42cf3417-1baf-4e88-a6be-e4dc1628ddbe">

**Comment by reeywhaar** [comment]
Oh, I see, these are two different pageSize, one in Meta, and one for the pages. We have it right there. PageSize is usize, and meta one in u32. Similar to bolt.

https://github.com/Reeywhaar/nut/blob/14d57bdb1eb217eb610c889d48ff58a7f6d59d28/src/page/mod.rs#L24
